### ISSUE TITLE
Publish to Microsoft Edge Add-ons store

### ISSUE THREAD

**Issue by uncenter** [catppuccin/github-file-explorer-icons#9]
- https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension#submit-your-extension-to-the-microsoft-edge-add-ons-website

Related to #8. We will need to set up a Catppuccin account for the Microsoft Edge Add-ons store, add the credentials as secrets, and add them as environment variables to the [release workflow's submit step](https://github.com/catppuccin/github-file-explorer-icons/blob/b590f37cf3246afab3c8d52b4801f2b3571ae7cb/.github/workflows/release.yml#L35-L44):

```yaml
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
          EDGE_ACCESS_TOKEN_URL: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
```
